### ISSUE TITLE
Add skins support.

### ISSUE THREAD

**Issue by kabalin** [lucisgit/moodle-filter_jwplayer#10]
Paid version of JW Player support skins and comes with 8 default ones. Would be good to have a plugin setting to select one them. For more details, see http://support.jwplayer.com/customer/portal/articles/1406968-using-jw-player-skins

The further elaboration of this feature could be a support of custom skins (via skin xml file uploading).

**Comment by fernandooliveira** [comment]
Support for skins would be a welcome feature. Other "Player Branding" features would also be very useful. More info here: http://support.jwplayer.com/customer/portal/articles/1406865-branding-your-player.
