### ISSUE TITLE
Priority reversed for links with multiple streams

### ISSUE THREAD

**Issue by owenbarritt** [lucisgit/moodle-filter_jwplayer#51]
Links containing multiple streams reverse the order (and hence the priority) of the streams when embedded in the player.

http://url.for/file.m3u8#http://url.for/file.smil#http://url.for/file.mp4

Would result the sources for the player being:

{file: http://url.for/file.smil}, {file: http://url.for/file.m3u8}, {file:  http://url.for/file.mp4}

Meaning the smil stream becomes prioritised even though the user specified the hls stream first.

**Comment by kabalin** [comment]
Merged for both branches, thanks for contributing the fix @owenbarritt!
