### ISSUE TITLE
Uncaught Error: No define call for jwplayer http://requirejs.org/docs/errors.html#nodefine

### ISSUE THREAD

**Issue by owenbarritt** [lucisgit/moodle-filter_jwplayer#55]
I've just tried the latest version and something looks to be wrong with the javascript.

Player no longer loads and console gives the following require.js error:

Uncaught Error: No define call for jwplayer
http://requirejs.org/docs/errors.html#nodefine

We're using the self-hosted setup and the jwplayer.js file looks to be being loaded by the browser ok

**Comment by kabalin** [comment]
Hmm, strange. You have a license key and went through upgrade procedure I guess.

**Comment by kabalin** [comment]
And you are not loading jwplayer.js anywhere outside plugin? (e.g. custom header)

**Comment by kabalin** [comment]
What about cloud version in configuration with your self-hosted key?

**Comment by owenbarritt** [comment]
Looks like this was just my error.  I thought I'd already upgraded the jwplayer library on the server as I know I'd tested and found the old plugin worked fine with the newer player.

Clearly must have only done that on the test server though...

Sorry, it's been a long day.

**Comment by kabalin** [comment]
OK, let me know if there are any other issues.
