### ISSUE TITLE
Publish on moodle.org/plugins

### ISSUE THREAD

**Issue by jojoob** [lucisgit/moodle-filter_jwplayer#6]
Maybe publish the plugin on moodle.org to reach more users and make it more 'offical'...

**Comment by edequal** [comment]
Anything for Moodle 2.5?

**Comment by kabalin** [comment]
Submitted to Moodle plugins list, waiting for approval now.

**Comment by kabalin** [comment]
It has been published, see https://moodle.org/plugins/view/filter_jwplayer for details.

**Comment by kabalin** [comment]
237 downloads in the last month (24/04/15) - did not expect it will be that popular :)
