### ISSUE TITLE
jwplayer.js being called on login/index.php even though no videos present

### ISSUE THREAD

**Issue by owenbarritt** [lucisgit/moodle-filter_jwplayer#60]
The filter looks to be running on the login/index.php page and adding the jwplayer.js reference even if there's no videos present (looks to only be if login instructions have been added).

This causes browser errors if "Use HTTPS for logins" is enabled due to mixed content as the library is loaded over HTTP.

**Comment by kabalin** [comment]
Thanks @owenbarritt for bug report. As workaround, eather make whole site using https, or use CDN (cloud) version of player, which is is loaded over https.

**Comment by owenbarritt** [comment]
As there's no video it's not a huge problem that it's being blocked.

Just spotted it while looking into another issue unrelated to jwplayer.
