### ISSUE TITLE
 Video doesn't play after clicking download button

### ISSUE THREAD

**Issue by jojoob** [lucisgit/moodle-filter_jwplayer#63]
1. Enable download video button in filter_jwplayer settings
2. Click the download button within a jwplayer window and download the file or cancel the download
3. Try to start video playback: The video will not be played

![screen shot 2016-11-07 at 12 15 16](https://cloud.githubusercontent.com/assets/4180675/20055981/2f750e7c-a4e4-11e6-8be4-3520911c961b.png)

**Comment by kabalin** [comment]
@jojoob thanks for the patch, I had to refactor it a bit and removed minifiled js from the commit https://github.com/lucisgit/moodle-filter_jwplayer/commit/c3342164c27a04649b861296ddbd0869038b8467. If you do some JS changes, please create pull request without minified module, I will build one myself before release. I will ask other contributors to do the same.
