### ISSUE TITLE
In Moodle 3.2, JW Player Filter is not triggered

### ISSUE THREAD

**Issue by tmkinn** [lucisgit/moodle-filter_jwplayer#65]
It seems like the VideoJS is outruling JW, anyhow, the JW player is not working.

We tried rtmp links, which works from elsewhere. Please do contact me if you need access to see the problem.

This is a pretty urgent matter for us, as we use a lot of video in our courses.

**Comment by kabalin** [comment]
Hi @tmkinn, thanks for reporting this. To be honest, we did not test plugin with 3.2 yet, so it has not been marked as 3.2 compatible on plugin page. But I understand this might affect all our users who upgraded to 3.2, so I will give this issue a high priority.

**Comment by multiplexer2** [comment]
In Moodle 3.2, JW Player should probably be installed as a 'Media Player' plugin in the /media/player/ folder.

**Comment by kabalin** [comment]
@multiplexer2 that is the plan, but does not seem like a quick thing to make this plugin using new media API. So, at this stage I will make it work for 3.2 as filter.

**Comment by tmkinn** [comment]
When you set this to high priority, does that mean that you are working on this now, and will possibly get a version out this week, or are we talking longer?

**Comment by kabalin** [comment]
@tmkinn I am looking at this now, but need some time to be able to indicate when this might be fixed.

**Comment by kabalin** [comment]
The plan is to roll out a new version addressing 3.2 issue this week.

**Comment by tmkinn** [comment]
Great!

**Comment by kabalin** [comment]
Lets keep the ticket open till the fix is released.

**Comment by tmkinn** [comment]
LOL! Sorry! That was not intended! I have too much power :)

**Comment by kabalin** [comment]
The version compatible with 3.2 has been [released](https://moodle.org/plugins/pluginversion.php?id=12948), please report any issues.
