### ISSUE TITLE
PHP Exception during installation of v. 7-0.6 in Moodle 3.2+

### ISSUE THREAD

**Issue by multiplexer2** [lucisgit/moodle-filter_jwplayer#66]
The plugin installation seems to be successfull, but the following PHP error occurs:

Default exception handler: Exception - Class 'filter_jwplayer_media' not found

Debug: \nError code: generalexceptionmessage\n* line 31 of /filter/jwplayer/settings.php: Error thrown\n* line 88 of /lib/classes/plugininfo/filter.php: call to include()\n* line 215 of /admin/settings/plugins.php: call to core\\plugininfo\\filter->load_settings()\n* line 7703 of /lib/adminlib.php: call to require()\n* line 22 of /admin/upgradesettings.php: call to admin_get_root()\n, referer: /admin/index.php?cache=0&confirmplugincheck=1

**Comment by kabalin** [comment]
Oh, that what happens when I ignore testing it on clean installation. Sorry. I have hidden 0.6+32 version for now, will fix the issue tomorrow morning and update the release.

**Comment by kabalin** [comment]
@multiplexer2, can you confirm when you see this error? During installation or when accessing plugin settings?

**Comment by multiplexer2** [comment]
It happens during upgrade and during a clean install. If I add the following line to settings.php everything seems to work as it should:

```
    require_once(__DIR__ . '/adminlib.php');
>  require_once(__DIR__ . '/classes/player.php');
    $jwplayer = new filter_jwplayer_media();
```

**Comment by kabalin** [comment]
The strange thing is that I am not getting that error on upgrade. Anyway, I have just published release where this is fixed https://moodle.org/plugins/pluginversion.php?id=12952
