### ISSUE TITLE
Compatibility problems with Moodle 3.2.2

### ISSUE THREAD

**Issue by multiplexer2** [lucisgit/moodle-filter_jwplayer#67]
The core_media_manager class now has a new constructor which needs a page object as a required argument.  This causes a PHP warning upon instantiation of the jwplayer filter:

Warning: Missing argument 1 for core_media_manager::__construct(), called in /filter/jwplayer/classes/manager.php on line 40 and defined in /media/classes/manager.php on line 128

Notice: Undefined variable: page in /media/classes/manager.php on line 129

**Comment by kabalin** [comment]
The change I did not expect to see in Moodle point release. It is critical or can wait till the proper JW Player media plugin?

**Comment by multiplexer2** [comment]
It seems like the player is still working. But the PHP warning is written to the log on every moodle pageload, which may have a negative effect on performance. HTML output will be broken for sites with  debugdisplay = 'Yes' and  debug = 'NORMAL' or above. Personally I would not dare to use the current version on a 3.2.2 production site.

**Comment by kabalin** [comment]
Any chance you can submit a pull request with a fix that would check moodle
version, and if it is > 3.2.2, then pass page instance as parameter
(otherwise call it without parameter)? I do not want a separate version for
3.2.2 only and explain people that it will not work with earlier 3.2.x, too
confusing and too much work given we will be switching to media plugin soon.

**Comment by multiplexer2** [comment]
I'm sorry but I'm not familiar with GIT development and pull requests. The overridden instance method must be declared with the same argument list as the instance method of the parent class. I've tested the code below in Moodle 3.2.2, and it seems to work well. But perhaps there are better ways to do it ... I don't know ...

`if ($CFG->version >= 2016120502) {

class filter_jwplayer_manager extends core_media_manager {

    public static function instance($page = null) {
        // Use the passed $page if given, otherwise the $PAGE global.
        if (!$page) {
            global $PAGE;
            $page = $PAGE;
        }
        if (self::$instance === null || ($page && self::$instance->page !== $page)) {
            self::$instance = new self($page);
        }
        return self::$instance;
    }

    protected function get_players() {
        $players = parent::get_players();
        array_unshift($players, new filter_jwplayer_media());
        $this->players = $players;
        return $this->players;
    }
}

} else {

class filter_jwplayer_manager extends core_media_manager {

    public static function instance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    protected function get_players() {
        $players = parent::get_players();
        array_unshift($players, new filter_jwplayer_media());
        $this->players = $players;
        return $this->players;
    }
}

}`

**Comment by kabalin** [comment]
Thanks @multiplexer2, I will see if I find time to refactor that and test properly. In fact, I had a look at the original commit https://github.com/moodle/moodle/commit/1abd43763c17d5e10ca17bb5cf567cfa4662d007 and it looks safe to me to use the plugin as it is and ignore the warning.

**Comment by xow** [comment]
I should have made the parameter optional, my bad. Didn't think of this. In truth a singleton's constructor should always be private. We shouldn't subclass core_media_manager at all See #69

**Comment by xow** [comment]
Added a fix https://github.com/lucisgit/moodle-filter_jwplayer/pull/68/files

**Comment by kabalin** [comment]
Released, thanks @multiplexer2  for reporting and @xow  for the fix.
