### ISSUE TITLE
JW7 3.2 should be a media plugin, not a filter

### ISSUE THREAD

**Issue by xow** [lucisgit/moodle-filter_jwplayer#69]
Media manager was not meant to be subclassed to add extra filters, instead you are supposed to create a media plugin. This was our bad for making the constructor protected

Thanks for working on this plugin!

**Comment by kabalin** [comment]
Yep, that is the plan to turn this into make a media plugin, 7-0.6+32 is a "ported" version of filter that would work with 3.2 while the proper media plugin is not ready, see https://github.com/lucisgit/moodle-filter_jwplayer/releases/tag/moodle-filter_jwplayer_7-0.6%2B32 for details.

**Comment by jproctor** [comment]
Found this issue, and [7-07+32](https://github.com/lucisgit/moodle-filter_jwplayer/releases/tag/moodle-filter_jwplayer_7-0.7%2B32) seems to work, at least for my non-DRM stuff (need to do some more digging). So I’m commenting here in case someone else comes in this way and forgets to check the [current release list](https://github.com/lucisgit/moodle-filter_jwplayer/releases) for updates.

**Comment by kabalin** [comment]
Media plugin is ready and awaiting approval in Moodle plugins directory. It is fine to start using it, though beware it is beta at the moment. See its [release notes](https://github.com/lucisgit/moodle-media_jwplayer/releases) for details.

https://github.com/lucisgit/moodle-media_jwplayer

**Comment by kabalin** [comment]
JW Player media plugin has been added to Moodle plugin directory: https://moodle.org/plugins/media_jwplayer
