### ISSUE TITLE
RTMP sources from Amazon Cloudfront will not play

### ISSUE THREAD

**Issue by stevefister** [lucisgit/moodle-filter_jwplayer#71]
Just upgraded my moodle installation and installed JWPlayer. It seems to play fine using a Cloudfront download URL, but when I use the Streaming distribution for RTMP, I get "ERROR LOADING PLAYER: No playable sources found" error. These RTMP urls were working just fine prior to the upgrade to JWPlayer. I have set the JWPlayer settings to play RTMP. Any ideas what could be the problem? Please note: The JWPlayer plugin is installed as a filter, not a multimedia plugin. The installation instructions say install as a filter, but I see in some commentary that it may be installed as a multimedia plugin now? Thanks.

**Comment by kabalin** [comment]
Yes, try Media plugin instead, it is now officially listed: https://moodle.org/plugins/media_jwplayer Regarding RTMP support, if you are using media plugin, make sure your Moodle has been upgraded to certain stable relese (see https://github.com/lucisgit/moodle-media_jwplayer/issues/1), also make sure that you have ticked the checkbox in the settings to support RTMP.
