### ISSUE TITLE
multiple calls to list_supported_extensions() in settings.php

### ISSUE THREAD

**Issue by danmarsden** [lucisgit/moodle-filter_jwplayer#8]
Hi guys, 

I'm being a very pedantic here.... but while reviewing this in the plugins db I noticed the settings.php file calls list_supported_extensions() 3 times - and although it doesn't hit the db it does do an array_merge which isn't the fastest PHP function in the world.... it would probably be more efficient to assign it to a var then re-use that var 3 times. 

Settings.php is called in a lot of places, so the more efficient we can make it, the better!

**Comment by kabalin** [comment]
Thanks @danmarsden for reporting. This is now fixed.
